// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "home": {
    "count": "Count",
    "input": {
      "label": "Write something",
      "message": "Text length",
      "placeholder": "Type something here..."
    },
    "profile": "Go to profile"
  },
  "shared": {
    "footer": {
      "message": "Made with ❤️ by Yuri"
    },
    "nav": {
      "link": {
        "home": "Home",
        "login": "Login",
        "register": "Register"
      }
    }
  }
}

export default Resources;
